Moves releases info to a releases page.
maliput/maliput_documentation pull request #110
Opened 2022-08-02 13:09 UTC by francocipollone

### Summary

Resolves #98

2022-08-02 13:19 UTC, francocipollone reviewed
I added some comments reflecting some changes that are needed in the documentation.
@agalbachicar Let me know if you see further changes to be applied.

2022-08-02 13:19 UTC, francocipollone commented on docs/releases.rst
> +  patch release ``(x - 1)``.
I think that creating releases branch won't be necessary anymore.

2022-08-02 13:19 UTC, francocipollone commented on docs/releases.rst
> +  :ref:`create-a-named-release-tarball` ).
We should remove everything related to S3. We are releasing via ros build farm now

2022-08-02 13:19 UTC, francocipollone commented on docs/releases.rst
> +* Upload the binary tarball to Amazon S3 bucket.
We should remove it.

Also info about releasing via bloom release should be added.

2022-08-02 13:19 UTC, francocipollone commented on docs/releases.rst
> +    tar -czvf ${CURRENT_BUNDLE_TARBALL_NAME} ${BUNDLE_NAME}
Remove it

2022-09-20 12:46 UTC, agalbachicar commented on docs/releases.rst
> +  patch release ``(x - 1)``.
Hmm, I think it will. Because when we start to support another ROS2 version we may opt to use packages that are not available in previous releases targeting a ROS2 - X release. I don't think we can have a linear history of releases.

2022-09-20 12:46 UTC, agalbachicar commented on docs/releases.rst
> +  :ref:`create-a-named-release-tarball` ).
Agreed.

2022-09-20 12:46 UTC, agalbachicar commented on docs/releases.rst
> +* Upload the binary tarball to Amazon S3 bucket.
Agreed.

2022-09-20 12:46 UTC, agalbachicar commented on docs/releases.rst
> +    tar -czvf ${CURRENT_BUNDLE_TARBALL_NAME} ${BUNDLE_NAME}
Agreed.

2022-09-27 13:55 UTC, francocipollone commented on docs/releases.rst
> +**IMPORTANT:** ``maliput`` **is still under actively development for so semantic versioning is not yet strictly followed for the** `1.X.Y` **versions.**
@agalbachicar Note this. I think that mentioning our willing to follow sem ver and stating that we aren't following for the moment it's ok. Wdyt?

2022-09-28 13:41 UTC, agalbachicar requested changes
Minor comments, overall it LGTM.

2022-09-28 13:41 UTC, agalbachicar commented on docs/releases.rst
> +will follow as much as possible the `ROS2 Versioning guidelines <https://docs.ros.org/en/foxy/Contributing/Developer-Guide.html#versioning>`_ .
```suggestion
will follow the `ROS2 Versioning guidelines <https://docs.ros.org/en/foxy/Contributing/Developer-Guide.html#versioning>`_ .
```

2022-09-28 13:41 UTC, agalbachicar commented on docs/releases.rst
> +**IMPORTANT:** ``maliput`` **is still under actively development for so semantic versioning is not yet strictly followed for the** `1.X.Y` **versions.**
Left a comment before that will help to clarify this. This is fine!

2022-09-28 13:45 UTC, francocipollone commented on docs/releases.rst
> +  patch release ``(x - 1)``.
Yeah right. Ok then, I will create the missing branches in the repos.

2022-09-29 13:46 UTC, agalbachicar approved these changes
LGTM

2022-09-29 14:01 UTC, merged