Adds info about creating a maliput_backend using maliput_sparse.
maliput/maliput_documentation pull request #126
Opened 2022-12-20 18:48 UTC by francocipollone

# 🎉 New feature

Related to #125 

## Summary

- What the title says
- Reorganize tutorial sections to be more scalable.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-12-21 17:25 UTC, agalbachicar requested changes
Some nits only.

2022-12-21 17:25 UTC, agalbachicar commented on docs/tutorials/maliput_sparse/creating_maliput_backend.rst
> +1. Implement a `maliput_sparse::parser::Parser`_: This pure virtual class is responsible for parsing an user-defined underlying road description format and serve the parsed data.
```suggestion
1. Implement a `maliput_sparse::parser::Parser`_: This abstract class is responsible for parsing an user-defined underlying road description format and serve the parsed data.
```

2022-12-21 17:25 UTC, agalbachicar commented on docs/tutorials/maliput_sparse/creating_maliput_backend.rst
> +   During the parsing process, the user will have to fill some data structures about the parsed lanes and connections between lanes, that will be used by the `maliput_sparse`_'s builder to create the
```suggestion
   During the parsing process, the user will have to fill some data structures about the parsed lanes and connections between them, that will be used by the `maliput_sparse`_'s builder to create the maliput backend.
```

2022-12-21 17:25 UTC, agalbachicar commented on docs/tutorials/maliput_sparse/creating_maliput_backend.rst
> +      };
Nit: I would suggest adding `std::vector<Connection> connections_;` and `std::unordered_map<Junction::Id, Junction> junctions_;` as class attributes to make it super clear that those are not magic attributes that come from `Parser`. Probably, it is worth adding in the constructor a reference to populate them there.

2022-12-21 17:25 UTC, agalbachicar commented on docs/tutorials/maliput_sparse/creating_maliput_backend.rst
> +3. Finally, it is recommended to provide a maliput::plugin::RoadNetworkLoader implementation with this new backend, in a way that it can be loaded in runtime to be used by packages like `maliput_viz`
```suggestion
3. Finally, it is recommended to provide a `maliput::plugin::RoadNetworkLoader` implementation with this new backend, in a way that it can be loaded in runtime to be used by packages like `maliput_viz`.
```

2022-12-21 20:16 UTC, francocipollone commented on docs/tutorials/maliput_sparse/creating_maliput_backend.rst
> +      };
You're right. Done

2022-12-22 12:52 UTC, agalbachicar approved these changes
LGTM

2022-12-22 14:09 UTC, merged