Improves getting started documentation.
maliput/maliput_documentation pull request #143
Opened 2023-10-31 18:14 UTC by francocipollone

# 🎉 New feature

## Summary
 - Improves installation instructions:
   - Bring pypi installation
 - Improves getting started page:
   - Provide info about bazel config

## Pendings:
 - [x] Bring maliput_examples repo to the getting started page
 - [x] Use multitab in the rest of the advanced/ getting started section

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

2023-11-07 02:48 UTC, francocipollone commented
To better review changes here there are the sphinx's output: 
[docs.zip](https://github.com/maliput/maliput_documentation/files/13275085/docs.zip)
(Doxygen output and gallery videos aren't uploaded to reduce zip size.)

You need unzip and load `index.html` with your browser

2023-11-07 06:59 UTC, agalbachicar requested changes
LGTM
Minor comments only.

2023-11-07 06:59 UTC, agalbachicar commented on docs/getting_started.rst
> +  The plugin architecture is in charge of loading the backend in runtime.
```suggestion
  The plugin architecture is in charge of loading the backend at runtime.
```

2023-11-07 06:59 UTC, agalbachicar commented on docs/getting_started.rst
> +  maliput::api::RoadPositionResult road_position_result = road_geometry->ToRoadPosition(maliput::api::InertialPosition{10.0, 0.0, 0.0});;
```suggestion
  const maliput::api::RoadPositionResult road_position_result = road_geometry->ToRoadPosition(maliput::api::InertialPosition{10.0, 0.0, 0.0});;
```

2023-11-07 06:59 UTC, agalbachicar commented on docs/getting_started.rst
> +Whether it was installed via binaries (via ROS 2 or PyPI) or from source code, the python interface is available to be used.
I don't think it is super clear this section. I propose the  following write up:

```rst
It is required to have `maliput`_ and at least one backend, e.g. `maliput_malidrive`_ ,installed to use the python interface. It is possible to install them via ROS 2 build farm or PyPI.


.. note::

  Please refer to :ref:`installation_label` for installing the packages via binaries.
```

2023-11-07 12:02 UTC, francocipollone commented on docs/getting_started.rst
> +Whether it was installed via binaries (via ROS 2 or PyPI) or from source code, the python interface is available to be used.
Indeed. thanks
Done.

2023-11-07 12:02 UTC, francocipollone commented on docs/getting_started.rst
> +  maliput::api::RoadPositionResult road_position_result = road_geometry->ToRoadPosition(maliput::api::InertialPosition{10.0, 0.0, 0.0});;
Done.

2023-11-07 12:02 UTC, francocipollone commented on docs/getting_started.rst
> +  The plugin architecture is in charge of loading the backend in runtime.
Done.

2023-11-10 07:24 UTC, agalbachicar approved these changes
LGTM

2023-11-10 11:44 UTC, merged