Adds info about python wheels.
maliput/maliput_documentation pull request #144
Opened 2023-11-07 03:34 UTC by francocipollone

# 🎉 New feature

## Summary
 - Adds info about maliput python wheels

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

2023-11-07 07:02 UTC, agalbachicar requested changes
PTAL.

2023-11-07 07:02 UTC, agalbachicar commented on docs/maliput_wheels_pypy_index.rst
> +As indicated in the :ref:`installation_label` section, `maliput` is supported to be installed via `pip`.
```suggestion
As indicated in the :ref:`installation_label` section, `maliput`_ is supported to be installed via `pip`_.
```

2023-11-07 07:02 UTC, agalbachicar commented on docs/maliput_wheels_pypy_index.rst
> +As indicated in the :ref:`installation_label` section, `maliput` is supported to be installed via `pip`.
Am I right? If so, then I think we are missing the _ in various places.

2023-11-07 07:02 UTC, agalbachicar commented on docs/maliput_wheels_pypy_index.rst
> +A custom docker image is used to build the wheels, and the dockerfile is defined at `maliput_infrastructure`_ repository where a GitHub Action is defined build and push the docker image to GHCR.
Can we add a link here?

2023-11-07 11:55 UTC, francocipollone commented on docs/maliput_wheels_pypy_index.rst
> +As indicated in the :ref:`installation_label` section, `maliput` is supported to be installed via `pip`.
By using `my_link`_ I reference this to a link mentioned in this page (see the bottom of the file).
I added a couple of missing _ however when I refer to maliput as the entire ecosystem (e.g. `maliput` maintainers) it doesn't make sense to have a link to maliput package.

2023-11-07 11:55 UTC, francocipollone commented on docs/maliput_wheels_pypy_index.rst
> +A custom docker image is used to build the wheels, and the dockerfile is defined at `maliput_infrastructure`_ repository where a GitHub Action is defined build and push the docker image to GHCR.
Good point.
Done!

2023-11-10 07:26 UTC, agalbachicar approved these changes
LGTM

2023-11-10 11:44 UTC, merged