Migrates documentation to read the docs.
maliput/maliput_documentation pull request #93
Opened 2022-06-27 20:57 UTC by francocipollone

Part of #92

2022-06-29 18:08 UTC, agalbachicar requested changes
Left some comments to clarify a bit the intent. PTAL

2022-06-29 18:31 UTC, francocipollone commented on README.md
> +The documentation is prepared and served in this repository, in order to be built using [Sphinx](https://www.sphinx-doc.org/en/master/) later on on [readthedocs](https://readthedocs.org/).
The three comments are related to this so let me respond here

- In the `main` branch we have the files necessaries for running compiling the package, I mean running `colcon build`.
This will trigger doxygen and generate the API documentation via doxygen. The `install/maliput_documentation/share/docs` folder is what is pushed to `rtd-pages`
- In the `rtd-pages` branch we will have 
  - The api docs generated via doxygen 
  - Sphinx configuration
  - .rst pages to be used by Sphynx
  (Note that at this point we haven't done nothing with sphinx)
- In readthedocs, sphinx's builder is run and the sphinx documentation is generated and that's what `readthedocs` is using for serving the page.

Note the difference with our previous approach for github pages. For the latter we ran sphinx-build ourselves and pointed github pages to the `index.html` file generated via sphinx.

As example you can use `rtd-pages` branch and check its content, and also check `gh-pages`. You will see that for the `gh-pages` the sphinx docs were already built while in the `rtd-pages` branch the sphinx command is to be run (that's why you see the typical sphinx related `conf.py` file there )


Please let me know if this answer your doubts @agalbachicar

2022-06-29 18:33 UTC, francocipollone commented on README.md
> +The documentation is prepared and served in this repository, in order to be built using [Sphinx](https://www.sphinx-doc.org/en/master/) later on on [readthedocs](https://readthedocs.org/).
We could add a cmake args for also running sphinx when doing colcon build to avoid an extra step when this is wanted to be built locally.

2022-07-01 13:21 UTC, francocipollone commented on README.md
> +The documentation is prepared and served in this repository, in order to be built using [Sphinx](https://www.sphinx-doc.org/en/master/) later on on [readthedocs](https://readthedocs.org/).
Let me know what you think @agalbachicar

2022-07-01 13:21 UTC, francocipollone commented on README.md
> +  ```
See https://github.com/maliput/maliput_documentation/pull/93#discussion_r910280541

2022-07-01 13:21 UTC, francocipollone commented on README.md
> +## Build Sphinx docs
See https://github.com/maliput/maliput_documentation/pull/93#discussion_r910280541

2022-07-01 17:16 UTC, agalbachicar commented on README.md
> +The documentation is prepared and served in this repository, in order to be built using [Sphinx](https://www.sphinx-doc.org/en/master/) later on on [readthedocs](https://readthedocs.org/).
Thanks a lot for the clarification.

There are a couple of things that I like and dislike at the same time :)

- It's great to not depend on sphinx to build the docs now because someone else would do it for us!
- It's really bad that we cannot out of the box compile the doucmentation as readthedocs would do because of not having the dependency and doing that extra step manually. It breaks the nice thing about having rosdep to take care of all of our dependencies.
- If we wanted to provide a convenient flag / command so cmake runs sphinx we would require that dependency which we are removing now.

One question, is it possible to push a bundle to readthedocs and serve it there as we were doing with github pages? Or does it only receives the rst files, the configuration and extra assets? If we can push the compiled bundle I think it is worth to do it because we would be in full control of the documentation generation process and that would allow us to audit it.

2022-07-01 18:00 UTC, francocipollone commented on README.md
> +The documentation is prepared and served in this repository, in order to be built using [Sphinx](https://www.sphinx-doc.org/en/master/) later on on [readthedocs](https://readthedocs.org/).
I see your point.

> is it possible to push a bundle to readthedocs and serve it there as we were doing with github pages?

The normal workflow of the readthedocs' documentation doesn't provide information about this kind of behavior you are suggesting. Always the documentation points you to let readtheddocs to build the docs, and even though I could try to find a workaround for this, I don't think this is possible, due to the following: "[Advertising](https://docs.readthedocs.io/en/latest/advertising/index.html#advertising) is the single largest source of funding for Read the Docs. " And I assume they need to build the docs to embed those ads:

<img src="https://user-images.githubusercontent.com/53065142/176946701-44e263c4-5692-48f8-b90a-b6e12bb83c86.png" width=200/ >

2022-07-04 07:08 UTC, agalbachicar commented on README.md
> +The documentation is prepared and served in this repository, in order to be built using [Sphinx](https://www.sphinx-doc.org/en/master/) later on on [readthedocs](https://readthedocs.org/).
OK, let's proceed as is. Thanks for investigating!

2022-07-04 07:08 UTC, agalbachicar approved these changes
LGTM

2022-07-05 12:17 UTC, francocipollone commented
closed in favor of https://github.com/maliput/maliput_documentation/pull/95 that contains these changes

2022-07-05 12:17 UTC, closed without merging