Improves some docs pages
maliput/maliput_documentation pull request #95
Opened 2022-06-29 21:40 UTC by francocipollone

### Summary

- Improves Gallery page
- Improves Documentation page
- Split documentation into api_documentation, design, and tutorials.

2022-07-01 17:21 UTC, agalbachicar requested changes
PTAL

2022-07-01 17:21 UTC, agalbachicar commented on docs/tutorials.rst
> +      <iframe src="html/deps/maliput_malidrive/html/tutorials.html" height="600px" width="900px"></iframe>
I don't think this is a good idea. I would just add a link to it rather than embedding the page. Also, note that the height and width break the layout readthedocs.

2022-07-01 20:46 UTC, francocipollone commented on docs/tutorials.rst
> +      <iframe src="html/deps/maliput_malidrive/html/tutorials.html" height="600px" width="900px"></iframe>
> Also, note that the height and width break the layout readthedocs.

I could adjust this in particular. 

However I went back and added just the links. See 943595c.

2022-07-04 07:09 UTC, agalbachicar approved these changes
LGTM

2022-07-05 12:12 UTC, merged